#!/bin/sh
final="$@"

# add ros path plugin if it does not already exist in the passed in arguments
if [ `expr "$final" : '.*libgazebo\_ros\_paths\_plugin\..*'` -eq 0 ]
then
    plugin_lib_path=`catkin_find libgazebo_ros_paths_plugin.so`
    if [ -z "$plugin_lib_path" ]
    then
        plugin_lib_path=`catkin_find libgazebo_ros_paths_plugin.dylib`
    fi
    if [ -z "$plugin_lib_path" ]
    then
        echo "Error: catkin_find cannot find libgazebo_ros_paths_plugin.so"
    fi
    final="$final -s $plugin_lib_path"
fi

# add ros api plugin if it does not already exist in the passed in arguments
if [ `expr "$final" : '.*libgazebo\_ros\_api\_plugin\..*'` -eq 0 ]
then
    plugin_lib_path=`catkin_find libgazebo_ros_api_plugin.so`
    if [ -z "$plugin_lib_path" ]
    then
        plugin_lib_path=`catkin_find libgazebo_ros_api_plugin.dylib`
    fi
    if [ -z "$plugin_lib_path" ]
    then
        echo "Error: catkin_find cannot find libgazebo_ros_api_plugin.so"
    fi
    final="$final -s $plugin_lib_path"
fi

setup_path=$(pkg-config --variable=prefix gazebo)/share/gazebo/
echo "$final"
. $setup_path/setup.sh && gzserver $final
